# Generated by Django 2.0.7 on 2018-07-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('named_id', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
    ]
