# Generated by Django 2.0.7 on 2018-07-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='named_id',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
