# Generated by Django 2.0.7 on 2018-07-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitors',
            old_name='session_start',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='visitors',
            name='page_views',
        ),
        migrations.AddField(
            model_name='visitors',
            name='aff_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='visitors',
            name='request_method',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='visitors',
            name='response_code',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
