# Generated by Django 2.0.7 on 2018-07-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_auto_20180706_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='request_method',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
