# Generated by Django 2.0.7 on 2018-07-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_auto_20180706_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='language',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
