# Generated by Django 2.0.7 on 2018-07-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_visitors_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
    ]
