# Generated by Django 2.0.7 on 2018-07-06 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_visitors_is_bot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitors',
            options={'verbose_name': 'Visitor', 'verbose_name_plural': 'Visitors'},
        ),
        migrations.RemoveField(
            model_name='visitors',
            name='response_code',
        ),
    ]
