# Generated by Django 2.0.7 on 2018-07-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='container_type',
            field=models.CharField(choices=[('bottle', 'bottle'), ('cap', 'cap'), ('cream', 'cream'), ('inhaler', 'inhaler'), ('pack', 'pack'), ('pill', 'pill'), ('sachet', 'sachet'), ('spray', 'spray'), ('tab', 'tab'), ('tablet', 'tablet'), ('tube', 'tube')], max_length=10),
        ),
    ]
