# Generated by Django 2.0.7 on 2018-07-08 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20180708_1317'),
        ('products', '0002_auto_20180708_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
            ],
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Producs', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='productcategory',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Products'),
        ),
    ]
