# Generated by Django 2.0.7 on 2018-07-08 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generic_name', '0001_initial'),
        ('products', '0003_auto_20180708_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGeneric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generic_name.GenericName')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Products')),
            ],
        ),
    ]
